### ISSUE TITLE
.

### ISSUE THREAD

**Issue by YAKUDZA1312** [ultra-marina/project-july2023#5]
Привіт все чудово) на конференцію не потрапив із-за роботи.Хотів спитати чи є якийсь додаток котрий зменьшує вміст svg.Та куди додавати свою svg та img в загальну чи окрему?

_Originally posted by @YAKUDZA1312 in https://github.com/ultra-marina/project-july2023/pull/3#discussion_r1278292361_

**Comment by ultra-marina** [comment]
Я користувалася ли ше icomoon (https://icomoon.io/) і svgomg (https://jakearchibald.github.io/svgomg/) - як нас навчали.
Свої зображення треба додавати до своєї папки (створити її в спільній папці img), svg бажано додати до спільного спрайту (icons.svg в папці img).
